# Generated by Django 2.0.3 on 2018-03-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_number',
            new_name='custs_number',
        ),
    ]
