# Generated by Django 2.0.3 on 2018-03-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Customer'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Customer'),
        ),
    ]
