# Generated by Django 2.0.3 on 2018-03-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20180324_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='symbol',
        ),
    ]
