# Generated by Django 2.0.3 on 2018-03-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20180324_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='customer',
        ),
    ]
