# Generated by Django 2.0.3 on 2018-03-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_portfolios_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customersportfolio', to='portfolio.Customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolios',
        ),
        migrations.AlterField(
            model_name='stock',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.Customer'),
        ),
    ]
