# Generated by Django 2.0.3 on 2018-03-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20180325_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='customerportfolio',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CustomerPortfolio',
        ),
    ]
