# Generated by Django 2.0.4 on 2018-04-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20180325_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='portfolio.Customer'),
        ),
    ]
